/// Flutter icons GithubIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GithubIcon
///      fonts:
///       - asset: fonts/GithubIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GithubIcon {
  GithubIcon._();

  static const _kFontFam = 'GithubIcon';

  static const IconData github = const IconData(0xe800, fontFamily: _kFontFam);
}
